name: Hello World Workflow

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, world"

  list-files:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: List Files
        run: ls -a

  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        run: git clone https://github.com/your-username/your-repo.git

